export { CoverSlide } from "./CoverSlide"
export { OdsSlide } from "./OdsSlide"
export { Ods7Slide } from "./Ods7Slide"
export { GoalsSlide } from "./GoalsSlide"
export { WindEnergySlide } from "./WindEnergySlide"
export { AerogeneratorSlide } from "./AerogeneratorSlide"
export { ImportanceSlide } from "./ImportanceSlide"
export { BrazilSlide } from "./BrazilSlide"
export { TeamSlide } from "./TeamSlide"
export { ConclusionSlide } from "./ConclusionSlide"
export { SlideNavigation, KeyboardHint } from "./SlideNavigation"
export { SlideLayout, SlideContainer, SlideHeader } from "./SlideLayout"
